#! /bin/bash

KERNEL_NAME=`uname --kernel-name`
NODENAME=`uname --nodename`
KERNEL_RELEASE=`uname --kernel-release`
KERNEL_VERSION=`uname --kernel-version`
MACHINE=`uname --machine`
PROCESSOR=`uname --processor`
HARDWARE_PLATFORM=`uname --hardware-platform`
OPERATING_SYSTEM=`uname --operating-system`

echo "kernel-name: $KERNEL_NAME"
echo "nodename: $NODENAME"
echo "kernel-release: $KERNEL_RELEASE"
echo "kernel-version: $KERNEL_VERSION"
echo "machine: $MACHINE"
echo "processor: $PROCESSOR"
echo "hardware-platform: $HARDWARE_PLATFORM"
echo "operating-system: $OPERATING_SYSTEM"

